import fs from "fs";
import path from "path";

/**
 * Get HTTP method color/emoji
 */
function getMethodBadge(method) {
  const badges = {
    "GET": "🟢 GET",
    "POST": "🔵 POST",
    "PUT": "🟡 PUT",
    "PATCH": "🟠 PATCH",
    "DELETE": "🔴 DELETE",
    "HEAD": "⚪ HEAD",
    "OPTIONS": "⚫ OPTIONS",
    "ALL": "🌈 ALL"
  };
  return badges[method] || `⚪ ${method}`;
}

/**
 * Group routes by base path
 */
function groupRoutes(routes) {
  const groups = {};

  routes.forEach(route => {
    // Extract base path (e.g., /api/users -> /api)
    const parts = route.path.split("/").filter(p => p);
    const basePath = parts.length > 0 ? `/${parts[0]}` : "/";

    if (!groups[basePath]) {
      groups[basePath] = [];
    }
    groups[basePath].push(route);
  });

  return groups;
}

/**
 * Get description for common endpoints
 */
function getEndpointDescription(method, path) {
  const pathLower = path.toLowerCase();

  // Common patterns
  if (pathLower.includes("/login")) return "User authentication";
  if (pathLower.includes("/register") || pathLower.includes("/signup")) return "User registration";
  if (pathLower.includes("/logout")) return "User logout";
  if (pathLower.includes("/profile")) return "User profile operations";
  if (pathLower.includes("/password")) return "Password management";

  // RESTful patterns
  if (method === "GET" && pathLower.includes("/:id")) return "Get single resource by ID";
  if (method === "GET") return "Retrieve resources";
  if (method === "POST") return "Create new resource";
  if (method === "PUT" || method === "PATCH") return "Update resource";
  if (method === "DELETE") return "Delete resource";

  return "API endpoint";
}

export function generateApiDoc(apiRoutes, outputDir) {
  // If no routes found, create a placeholder doc
  if (!apiRoutes || apiRoutes.length === 0) {
    const content = `<div align="center">

# 🔌 API Documentation

> **No API routes detected**

</div>

---

## ℹ️ Information

No API endpoints were found in this project. This could mean:

- This is a frontend-only application
- API routes are defined in a non-standard way
- Routes are in files not scanned by the detector

### Supported Patterns

The API detector looks for these patterns:

\`\`\`javascript
// Express app routes
app.get('/api/users', ...)
app.post('/api/users', ...)

// Express router
router.get('/users', ...)
router.post('/users', ...)

// Route chaining
router.route('/users')
  .get(...)
  .post(...)
\`\`\`

### Scanned Directories

- \`/routes\`
- \`/api\`
- \`/src/routes\`
- \`/src/api\`
- \`/server\`
- \`/backend\`
- \`/backend/routes\`

---

<div align="center">

**Generated by [repo-docgen](https://www.npmjs.com/package/repo-docgen)** 🚀

</div>
`;

    fs.writeFileSync(path.join(outputDir, "API.md"), content);
    return;
  }

  // Generate full API documentation
  const grouped = groupRoutes(apiRoutes);
  const totalRoutes = apiRoutes.length;
  const methods = [...new Set(apiRoutes.map(r => r.method))];

  let content = `<div align="center">

# 🔌 API Documentation

> **${totalRoutes} endpoint${totalRoutes !== 1 ? 's' : ''} detected across ${Object.keys(grouped).length} base path${Object.keys(grouped).length !== 1 ? 's' : ''}**

</div>

---

## 📊 Overview

**Total Endpoints:** ${totalRoutes}

**HTTP Methods Used:** ${methods.map(m => getMethodBadge(m).split(' ')[1]).join(', ')}

---

## 📋 Endpoints

`;

  // Sort groups by base path
  const sortedGroups = Object.keys(grouped).sort();

  sortedGroups.forEach(basePath => {
    const routes = grouped[basePath];

    content += `### ${basePath === "/" ? "Root" : basePath}\n\n`;

    // Sort routes by method and path
    routes.sort((a, b) => {
      if (a.method !== b.method) {
        const order = ["GET", "POST", "PUT", "PATCH", "DELETE"];
        return order.indexOf(a.method) - order.indexOf(b.method);
      }
      return a.path.localeCompare(b.path);
    });

    routes.forEach(route => {
      const description = getEndpointDescription(route.method, route.path);
      const badge = getMethodBadge(route.method);
      const fileInfo = route.file ? ` · \`${route.file}\`` : "";

      content += `#### ${badge} \`${route.path}\`\n\n`;
      content += `${description}${fileInfo}\n\n`;

      // Add example request/response placeholders
      if (route.method === "POST" || route.method === "PUT" || route.method === "PATCH") {
        content += `<details>\n<summary>Request Example</summary>\n\n`;
        content += `\`\`\`json\n{\n  // Request body\n}\n\`\`\`\n\n</details>\n\n`;
      }

      content += `<details>\n<summary>Response Example</summary>\n\n`;
      content += `\`\`\`json\n{\n  "success": true,\n  "data": {}\n}\n\`\`\`\n\n</details>\n\n`;
      content += `---\n\n`;
    });
  });

  content += `## 📝 Notes

- This documentation was automatically generated by analyzing your code
- Request/response examples are placeholders and should be updated
- Add JSDoc comments to your route handlers for better documentation

---

## 🔧 Testing

You can test these endpoints using:

- **cURL**
  \`\`\`bash
  curl -X GET http://localhost:3000/api/endpoint
  \`\`\`

- **Postman** - Import this project and test endpoints interactively

- **Thunder Client** - VS Code extension for API testing

---

<div align="center">

**Generated by [repo-docgen](https://www.npmjs.com/package/repo-docgen)** 🚀

</div>
`;

  fs.writeFileSync(path.join(outputDir, "API.md"), content);
}
